spring.application.name=usermanagement
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagement_db
spring.datasource.username=susman
spring.datasource.password=

# Hibernate Configuration
# 'udpate' will automatically create the database tables based on the entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect